codeowners

diff --git a/.github/workflows/bump_dependent_charms.yaml b/.github/workflows/bump_dependent_charms.yaml
--- a/.github/workflows/bump_dependent_charms.yaml
+++ b/.github/workflows/bump_dependent_charms.yaml
@@ -30,9 +30,9 @@ jobs:
     strategy:
       matrix:
         repo:
-          - canonical/mongodb-operator
+          #- canonical/mongodb-operator
           #- canonical/mongodb-k8s-operator
-          #- canonical/mongos-k8s-operator
+          - canonical/mongos-k8s-operator
           #- canonical/mongos-operator
 
     permissions:
@@ -55,11 +55,7 @@ jobs:
           PREV_TAG=$(git describe --tags --abbrev=0 "${VERSION}"^)
           VERSION_CONTENT=$(git log --pretty=format:"- %h %s" "${PREV_TAG}..${VERSION}" | sed -E 's/\(#([0-9]+)\)/[#\1](https:\/\/github.com\/canonical\/mongo-single-kernel-library\/pull\/\1)/')
 
-          {
-            echo "VERSION_CONTENT<<EOF"
-            echo "${VERSION_CONTENT}"
-            echo "EOF"
-          } >> "${GITHUB_ENV}"
+          echo "VERSION_CONTENT=$((VERSION_CONTENT))" >> "$GITHUB_ENV"
 
       - name: Checkout target repo
         uses: actions/checkout@v6
@@ -110,6 +106,11 @@ jobs:
 
       - name: Commit changes
         run: |
+          if git show-ref --verify --quiet "refs/heads/${PR_BRANCH}"; then
+            echo "ERROR: Branch '${PR_BRANCH}' already exists. Refusing to overwrite it."
+            exit 1
+          fi
+
           git checkout -b "${PR_BRANCH}"
           git add pyproject.toml poetry.lock
           git commit -m "Bump ${DEP_NAME} to version ${VERSION}"
@@ -126,9 +127,14 @@ jobs:
             ### What's Changed
             ${{ env.VERSION_CONTENT }}"
 
+          REVIEWERS=$(grep ".github/workflows/bump_dependent_charms.yaml" .github/CODEOWNERS \
+                      | awk '{for(i=2;i<=NF;i++) print substr($i,2)}' \
+                      | sort -u \
+                      | paste -sd "," -)
+
           gh pr create \
             --title "patch: Bump ${DEP_NAME} to ${VERSION}" \
             --body "${BODY}" \
             --base ${{ env.BASE_BRANCH }}  \
             --head "${PR_BRANCH}" \
-            --reviewer Mehdi-Bendriss,Gu1nness,patriciareinoso
+            --reviewer "${REVIEWERS}"
