patch(DPE-9343): ARM Support on MongoDB 7 (#222)
Co-authored-by: Mehdi Bendriss <mehdi.bendriss@canonical.com>

diff --git a/.github/workflows/integration_test.yaml b/.github/workflows/integration_test.yaml
--- a/.github/workflows/integration_test.yaml
+++ b/.github/workflows/integration_test.yaml
@@ -22,6 +22,10 @@ jobs:
           sudo snap install go --classic
           go install github.com/snapcore/spread/cmd/spread@latest
           pipx install tox poetry
+      - name: Install deps
+        run: |
+          sudo apt update
+          sudo apt install -y  build-essential python3-dev libldap-dev libsasl2-dev
       - name: Collect spread jobs
         id: collect-jobs
         shell: python
@@ -30,9 +34,15 @@ jobs:
           import pathlib
           import os
           import subprocess
+          event_name = "${{ github.event_name }}"
+          if event_name == 'workflow_dispatch':
+              pattern = "github-ci"
+          else:
+              # Selects only amd64 jobs.
+              pattern = "github-ci:...amd64..."
           spread_jobs = (
               subprocess.run(
-                [pathlib.Path.home() / "go/bin/spread", "-list", "github-ci"],
+                [pathlib.Path.home() / "go/bin/spread", "-list", pattern],
                 capture_output=True,
                 check=True,
                 text=True,
@@ -46,7 +56,7 @@ jobs:
               _, runner, task = job.split(":")
               # Example: "test_charm.py"
               task = task.removeprefix("tests/spread/")
-              if runner.endswith("-arm"):
+              if "arm64" in runner:
                   architecture = "arm64"
               else:
                   architecture = "amd64"
@@ -65,12 +75,12 @@ jobs:
           with open(os.environ["GITHUB_OUTPUT"], "a") as file:
               file.write(output)
       - name: Generate Allure default test results
-        if: ${{ github.event_name == 'schedule' && github.run_attempt == '1' }}
+        if: ${{ github.event_name == 'workflow_dispatch' && github.run_attempt == '1' }}
         run: tox run -e integration -- tests/integration --allure-default-dir=allure-default-results
       - name: Upload Allure default results
         # Default test results in case the integration tests time out or runner set up fails
         # (So that Allure report will show "unknown"/"failed" test result, instead of omitting the test)
-        if: ${{ github.event_name == 'schedule' && github.run_attempt == '1' }}
+        if: ${{ github.event_name == 'workflow_dispatch' && github.run_attempt == '1' }}
         uses: actions/upload-artifact@v4
         with:
           name: allure-default-results-integration-test
@@ -110,12 +120,6 @@ jobs:
         with:
           pattern: ${{ inputs.artifact-prefix }}-*
           merge-multiple: true
-      - name: Override lxd image
-        timeout-minutes: 2
-        id: override-lxd
-        run: |
-          sudo lxc image copy ubuntu:568f69ff1166 local:
-          sudo lxc image alias create "juju/ubuntu@22.04/amd64" 568f69ff1166
       - name: Run spread job
         timeout-minutes: 180
         id: spread
@@ -133,7 +137,7 @@ jobs:
         # Only upload results from one spread system & one spread variant
         # Allure can only process one result per pytest test ID. If parameterization is done via
         # spread instead of pytest, there will be overlapping pytest test IDs.
-        if: ${{ (success() || (failure() && steps.spread.outcome == 'failure')) && startsWith(matrix.job.spread_job, 'github-ci:') && github.event_name == 'schedule' && github.run_attempt == '1' }}
+        if: ${{ (success() || (failure() && steps.spread.outcome == 'failure')) && startsWith(matrix.job.spread_job, 'github-ci:') && contains(matrix.job.spread_job, 'amd64') && github.event_name == 'workflow_dispatch' && github.run_attempt == '1' }}
         uses: actions/upload-artifact@v4
         with:
           name: allure-results-integration-test-${{ matrix.job.name_in_artifact }}
@@ -155,6 +159,10 @@ jobs:
         timeout-minutes: 1
         if: ${{ success() || (failure() && steps.spread.outcome == 'failure') }}
         run: sudo juju status --color --relations | tee ~/logs/juju-status.txt
+      - name: juju status (YAML)
+        timeout-minutes: 1
+        if: ${{ success() || (failure() && steps.spread.outcome == 'failure') }}
+        run: sudo juju status --format yaml --color --relations --storage | tee ~/logs/juju-status-yaml.txt
       - name: juju debug-log
         timeout-minutes: 3
         if: ${{ success() || (failure() && steps.spread.outcome == 'failure') }}
@@ -175,3 +183,185 @@ jobs:
         timeout-minutes: 1
         if: ${{ success() || (failure() && steps.spread.outcome == 'failure') }}
         run: df --human-readable
+
+  allure-report:
+    # TODO future improvement: use concurrency group for job
+    name: Publish Allure report
+    if: ${{ !cancelled() && github.event_name == 'workflow_dispatch' && github.run_attempt == '1' }}
+    needs:
+      - integration-test
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    steps:
+      - name: Parse branch name
+        id: branch
+        shell: python
+        run: |
+          import os
+
+          if not "${{ github.ref }}".startswith("refs/heads/"):
+              raise Exception(
+                  "Allure Report generation assumes `workflow_dispatch` is triggered on a branch"
+              )
+          output = f"branch={'${{ github.ref_name }}'.replace('/', '_')}"
+          print(output)
+          with open(os.environ["GITHUB_OUTPUT"], "a") as file:
+              file.write(output)
+      - name: Download Allure
+        # Following instructions from https://allurereport.org/docs/install-for-linux/#install-from-a-deb-package
+        run: gh release download --repo allure-framework/allure2 --pattern 'allure_*.deb'
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Install Allure
+        run: |
+          sudo apt-get update
+          sudo apt-get install ./allure_*.deb -y
+      # For first run, manually create branch with no history
+      # (e.g.
+      # git checkout --orphan gh-pages-beta
+      # git rm -rf .
+      # touch .nojekyll
+      # git add .nojekyll
+      # git commit -m "Initial commit"
+      # git push origin gh-pages-beta
+      # )
+      - name: Checkout GitHub pages branch
+        uses: actions/checkout@v4
+        with:
+          ref: gh-pages-beta
+          path: repo/
+      - name: Download default test results
+        # Default test results in case the integration tests time out or runner set up fails
+        # (So that Allure report will show "unknown"/"failed" test result, instead of omitting the test)
+        uses: actions/download-artifact@v4
+        with:
+          path: allure-default-results/
+          name: allure-default-results-integration-test
+      - name: Download test results
+        uses: actions/download-artifact@v4
+        with:
+          path: allure-results/
+          pattern: allure-results-integration-test-*
+          merge-multiple: true
+      - name: Combine Allure default results & actual results
+        # For every test: if actual result available, use that. Otherwise, use default result
+        # So that, if actual result not available, Allure report will show "unknown"/"failed" test result
+        # instead of omitting the test
+        shell: python
+        run: |
+          import dataclasses
+          import json
+          import pathlib
+
+
+          @dataclasses.dataclass(frozen=True)
+          class Result:
+              test_case_id: str
+              path: pathlib.Path
+
+              def __eq__(self, other):
+                  if not isinstance(other, type(self)):
+                      return False
+                  return self.test_case_id == other.test_case_id
+
+
+          actual_results = pathlib.Path("allure-results")
+          default_results = pathlib.Path("allure-default-results")
+
+          results: dict[pathlib.Path, set[Result]] = {
+              actual_results: set(),
+              default_results: set(),
+          }
+          for directory, results_ in results.items():
+              for path in directory.glob("*-result.json"):
+                  with path.open("r") as file:
+                      id_ = json.load(file)["testCaseId"]
+                  results_.add(Result(id_, path))
+
+          actual_results.mkdir(exist_ok=True)
+
+          missing_results = results[default_results] - results[actual_results]
+          for default_result in missing_results:
+              # Move to `actual_results` directory
+              default_result.path.rename(actual_results / default_result.path.name)
+      - name: Load test report history
+        run: |
+          mkdir -p repo/${{ steps.branch.outputs.branch }}/
+          if [[ -d repo/${{ steps.branch.outputs.branch }}/_latest/history/ ]]
+          then
+            echo 'Loading history'
+            cp -r repo/${{ steps.branch.outputs.branch }}/_latest/history/ allure-results/
+          fi
+      - name: Create executor.json
+        shell: python
+        run: |
+          # Reverse engineered from https://github.com/simple-elf/allure-report-action/blob/eca283b643d577c69b8e4f048dd6cd8eb8457cfd/entrypoint.sh
+          import json
+
+          DATA = {
+              "name": "GitHub Actions",
+              "type": "github",
+              "buildOrder": ${{ github.run_number }},  # TODO future improvement: use run ID
+              "buildName": "Run ${{ github.run_id }}",
+              "buildUrl": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
+              "reportUrl": "../${{ github.run_number }}/",
+          }
+          with open("allure-results/executor.json", "w") as file:
+              json.dump(DATA, file)
+      - name: Generate Allure report
+        run: allure generate
+      - name: Create top-level index.html
+        shell: python
+        run: |
+          DATA = """<!DOCTYPE html>
+          <meta charset="utf-8">
+          <ul id="branches"></ul>
+          <style>
+              ul {
+                  font-size: 2rem;
+              }
+          </style>
+          <script type="module">
+              const response = await fetch("https://api.github.com/repos/${{ github.repository }}/contents?ref=gh-pages-beta", {
+                  headers: {
+                      "Accept": "application/vnd.github.object+json",
+                      "X-GitHub-Api-Version": "2022-11-28",
+                  }
+              });
+              const result = await response.json();
+              let branches = "";
+              for (const entry of result["entries"]) {
+                  if (entry["type"] !== "dir") {
+                      continue;
+                  }
+                  branches += `<li><a href="${entry["path"]}/">${entry["path"]}</a></li>`;
+              }
+              document.getElementById("branches").innerHTML = branches;
+          </script>
+          """
+          with open("repo/index.html", "w") as file:
+              file.write(DATA)
+      - name: Create branch index.html
+        shell: python
+        run: |
+          DATA = """<!DOCTYPE html>
+          <meta charset="utf-8">
+          <meta http-equiv="cache-control" content="no-cache">
+          <meta http-equiv="refresh" content="0; url=${{ github.run_number }}">
+          """
+          with open("repo/${{ steps.branch.outputs.branch }}/index.html", "w") as file:
+              file.write(DATA)
+      - name: Update GitHub pages branch
+        working-directory: repo/${{ steps.branch.outputs.branch }}/
+        # TODO future improvement: commit message
+        run: |
+          mkdir '${{ github.run_number }}'
+          rm -f _latest
+          ln -s '${{ github.run_number }}' _latest
+          cp -r ../../allure-report/. _latest/
+          git add ..
+          git config user.name "GitHub Actions"
+          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
+          git commit -m "Allure report ${{ github.run_number }}"
+          # Uses token set in checkout step
+          git push origin gh-pages-beta
